export const enum Getters {
	GET_FULL_NAME = 'GET_FULL_NAME',
	GET_EMAIL = 'GET_EMAIL',
	GET_PHONE_NUMBER = 'GET_PHONE_NUMBER',
}

export const enum Actions {
	SET_FULL_NAME = 'SET_FULL_NAME',
	SET_EMAIL = 'SET_EMAIL',
	SET_PHONE_NUMBER = 'SET_PHONE_NUMBER',
	SUBMIT_FORM = 'SUBMIT_FORM',
	CLEAR_FORM_STATE = 'CLEAR_FORM_STATE',
}

export const enum Mutations {
	MUTATE_FULL_NAME = 'MUTATE_FULL_NAME',
	MUTATE_EMAIL = 'MUTATE_EMAIL',
	MUTATE_PHONE_NUMBER = 'MUTATE_PHONE_NUMBER',
}
